### ISSUE TITLE
code does not seem to build with brotli? v1.0.2

### ISSUE THREAD

**Issue by nimendra** [kristoferbaxter/preact-hn#29]
Error: Command failed: bro -q 11 --input ...

```
 at checkExecSyncError (child_process.js:601:13)
    at execSync (child_process.js:641:13)
    at brotliFile (/.../dev/preact-hn/scripts/minify.js:32:3)
    at optimizeFileDelivery (/.../dev/preact-hn/scripts/minify.js:45:7)
    at /.../dev/preact-hn/scripts/minify.js:59:5
    at Object.<anonymous> (/.../dev/preact-hn/scripts/minify.js:67:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
```

**Comment by kristoferbaxter** [comment]
Hmm, seems to be failing on brotli encoding.

Can you verify that you can encode arbitrary files? `bro -q 11 --input ${filePath} --output ${filePath + '.br'}`

If this fails it indicates an issue with the installation of brotli.

**Comment by stereobooster** [comment]
We can use WASM implementation instead of external dependency https://github.com/dfrankland/wasm-brotli

**Comment by kristoferbaxter** [comment]
Great idea @stereobooster – Will take a look.

**Comment by nimendra** [comment]
@stereobooster @kristoferbaxter any chance we'd see a branch that uses WASM? Thanks

**Comment by kristoferbaxter** [comment]
A small checkin to hopefully allow for installation again was posted with #30. Will continue to leave this open since I'd like to have a seperate branch for looking into `wasm-brotli`.

**Comment by nimendra** [comment]
Works! Thanks
